<a href="https://colab.research.google.com/github/itsNisarg/DeepLearning/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

In [ ]:
import torch

In [ ]:
tensor = torch.arange(12, dtype=torch.float32)

In [ ]:
tensor.numel()      # number of elements in the tensor

12

In [ ]:
tensor.shape    # the tensor dimensions

torch.Size([12])

In [ ]:
zero_t = torch.zeros(2,3,4)

In [ ]:
one_t = torch.ones(2,3,4)

In [ ]:
rand_t = torch.randn(2,3)

In [ ]:
exp_t = torch.exp(rand_t)

In [ ]:
torch.cat([zero_t, one_t], dim=0).shape, torch.cat([zero_t, one_t], dim=1).shape, torch.cat([zero_t, one_t], dim=2).shape

(torch.Size([4, 3, 4]), torch.Size([2, 6, 4]), torch.Size([2, 3, 8]))

In [ ]:
x = torch.tensor([1,2,3]).reshape(-1,1)
y = torch.tensor([1,2]).reshape(1,-1)

In [ ]:
x, y

(tensor([[1],
         [2],
         [3]]),
 tensor([[1, 2]]))

In [ ]:
id(x), id(y)

(140304241366016, 140300019489504)

In [ ]:
x = x + y

In [ ]:
x, id(x)

(tensor([[2, 3],
         [3, 4],
         [4, 5]]),
 140304241364816)

In [ ]:
x += y

In [ ]:
x, id(x)

(tensor([[3, 5],
         [4, 6],
         [5, 7]]),
 140304241364816)

In [ ]:
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
B = A.clone()

$A \odot B = A ⋆ B$ is called the Hadamard Product of Tensors

In [ ]:
print(A * B)

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [ ]:
A.sum(axis=0), A.sum(axis=1)    # reduction sum

(tensor([12., 15., 18., 21.]), tensor([ 6., 22., 38.]))

In [ ]:
A.sum(axis=0, keepdims=True), A.sum(axis=1, keepdims=True)   # non-reduction sum

(tensor([[12., 15., 18., 21.]]),
 tensor([[ 6.],
         [22.],
         [38.]]))

In [ ]:
A / A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [ ]:
A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.]]))

In [ ]:
x = torch.tensor([1,2,3], dtype=torch.float32)
y = torch.ones(3)

In [ ]:
x, y, torch.dot(y, x)

(tensor([1., 2., 3.]), tensor([1., 1., 1.]), tensor(6.))

In [ ]:
A.shape, B.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
y @ A, A.T @ y, A.T @ B, A @ B.T

(tensor([12., 15., 18., 21.]),
 tensor([12., 15., 18., 21.]),
 tensor([[ 80.,  92., 104., 116.],
         [ 92., 107., 122., 137.],
         [104., 122., 140., 158.],
         [116., 137., 158., 179.]]),
 tensor([[ 14.,  38.,  62.],
         [ 38., 126., 214.],
         [ 62., 214., 366.]]))

In [ ]:
torch.norm(A)

tensor(22.4944)

---

# UCI ML Repo Dataset

In [ ]:
!pip install -q ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
abalone = fetch_ucirepo(id=1)

# data (as pandas dataframes)
X = abalone.data.features
y = abalone.data.targets

In [ ]:
# variable information
print(abalone.variables)

             name     role         type demographic  \
0             Sex  Feature  Categorical        None
1          Length  Feature   Continuous        None
2        Diameter  Feature   Continuous        None
3          Height  Feature   Continuous        None
4    Whole_weight  Feature   Continuous        None
5  Shucked_weight  Feature   Continuous        None
6  Viscera_weight  Feature   Continuous        None
7    Shell_weight  Feature   Continuous        None
8           Rings   Target      Integer        None

                   description  units missing_values
0         M, F, and I (infant)   None             no
1    Longest shell measurement     mm             no
2      perpendicular to length     mm             no
3           with meat in shell     mm             no
4                whole abalone  grams             no
5               weight of meat  grams             no
6  gut weight (after bleeding)  grams             no
7            after being dried  grams             no
8  +1.5 gives the age in years   None             no

In [ ]:
X.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055

Sex                object
Length            float64
Diameter          float64
Height            float64
Whole_weight      float64
Shucked_weight    float64
Viscera_weight    float64
Shell_weight      float64
dtype: object